/* TRIGGER */

CREATE TABLE PRODUTOS(
 IDPRODUTO INT IDENTITY PRIMARY KEY,
 NOME VARCHAR(50) NOT NULL, 
 CATEGORIA VARCHAR(30) NOT NULL,
 PRECO NUMERIC(10,2) NOT NULL

);
GO

CREATE TABLE HISTORICO(
	 IDPERACAO INT  PRIMARY KEY IDENTITY,
	 PRODUTO VARCHAR(50) NOT NULL, 
	 CATEGORIA VARCHAR(30) NOT NULL,
	 PRECOANTIGO NUMERIC(10,2) NOT NULL,
	 PRECONOVO NUMERIC(10,2) NOT NULL,
	 DATA DATETIME,
	 USUARIO VARCHAR(30),
	 MENSAGEM VARCHAR(100)

);
GO

INSERT INTO PRODUTOS VALUES('LIVRO SQL SERVER', 'LIVROS', 98.00)
INSERT INTO PRODUTOS VALUES('LIVRO ORACLE', 'LIVROS', 50.00)
INSERT INTO PRODUTOS VALUES('LICENÇA POWER CENTER', 'SOFTWARES', 45000.00)
INSERT INTO PRODUTOS VALUES('NOTEBOOK I7', 'COMPUTADORES', 3100.00)
INSERT INTO PRODUTOS VALUES('LIVRO BUSINESS INTELIGENCE ', 'LIVROS', 90.00)

SELECT*FROM PRODUTOS
SELECT*FROM HISTORICO


/*VERIFICANDO O USUÁRIO DO BANCO*/
SELECT SUSER_NAME()
GO

/* TRIGGER DE DADOS - DML( DATA MANIPULATION LANGUAGE */

CREATE TRIGGER TRG_ATUALIZA_PRECO 
ON DBO.PRODUTOS
FOR UPDATE
AS 
    DECLARE @IDPRODUTO INT
	DECLARE @PRODUTO VARCHAR(30)
	DECLARE @CATEGORIA VARCHAR(10)
	DECLARE @PRECO NUMERIC(10,2)
	DECLARE @PRECONOVO NUMERIC(10,2)
	DECLARE @DATA DATETIME
	DECLARE @USUARIO VARCHAR(30)
	DECLARE @ACAO VARCHAR(100)

	
	--PRIMEIRO BLOCO

	SELECT @IDPRODUTO = IDPRODUTO FROM inserted
	SELECT @PRODUTO = NOME FROM inserted
	SELECT @CATEGORIA = CATEGORIA FROM inserted
	SELECT @PRECO = PRECO FROM	deleted
	SELECT @PRECONOVO = PRECO FROM inserted
	
	--SEGUNDO BLOCO
     SET @DATA  = GETDATE()
	 SET @USUARIO = SUSER_NAME()
	 SET @ACAO = 'VALOR INSERIDO PELA TRIGGER TRG_ATUALIZA_PRECO'


	 INSERT INTO HISTORICO 
	 (PRODUTO, CATEGORIA, PRECOANTIGO, PRECONOVO, DATA,USUARIO, MENSAGEM)
	 VALUES
	 (@PRODUTO, @CATEGORIA, @PRECO, @PRECONOVO, @DATA, @USUARIO, @ACAO)

	 PRINT 'TRIGGER EXECUTADA COM SUCESSO'
GO

/*EXECUTANDO UM UPDATE*/
UPDATE PRODUTOS SET NOME = 'LIVRO C#'
WHERE IDPRODUTO = 1
GO

SELECT * FROM PRODUTOS
SELECT * FROM HISTORICO


/* PROGRAMANDO A TRIGGER EM UMA COLUNA */
DROP TRIGGER TRG_ATUALIZA_PRECO
GO

CREATE TRIGGER TRG_ATUALIZA_PRECO 
ON DBO.PRODUTOS
FOR UPDATE AS 
IF UPDATE(PRECO)
BEGIN

    DECLARE @IDPRODUTO INT
	DECLARE @PRODUTO VARCHAR(30)
	DECLARE @CATEGORIA VARCHAR(10)
	DECLARE @PRECO NUMERIC(10,2)
	DECLARE @PRECONOVO NUMERIC(10,2)
	DECLARE @DATA DATETIME
	DECLARE @USUARIO VARCHAR(30)
	DECLARE @ACAO VARCHAR(100)

	
	--PRIMEIRO BLOCO

	SELECT @IDPRODUTO = IDPRODUTO FROM inserted
	SELECT @PRODUTO = NOME FROM inserted
	SELECT @CATEGORIA = CATEGORIA FROM inserted
	SELECT @PRECO = PRECO FROM	deleted
	SELECT @PRECONOVO = PRECO FROM inserted
	
	--SEGUNDO BLOCO
     SET @DATA  = GETDATE()
	 SET @USUARIO = SUSER_NAME()
	 SET @ACAO = 'VALOR INSERIDO PELA TRIGGER TRG_ATUALIZA_PRECO'


	 INSERT INTO HISTORICO 
	 (PRODUTO, CATEGORIA, PRECOANTIGO, PRECONOVO, DATA,USUARIO, MENSAGEM)
	 VALUES
	 (@PRODUTO, @CATEGORIA, @PRECO, @PRECONOVO, @DATA, @USUARIO, @ACAO)

	 PRINT 'TRIGGER EXECUTADA COM SUCESSO'
END
GO

UPDATE PRODUTOS SET PRECO = 300.00
WHERE IDPRODUTO = 2
GO 

UPDATE PRODUTOS SET NOME = 'LIVRO JAVA'
WHERE IDPRODUTO = 2
GO 

SELECT *FROM HISTORICO